### ISSUE TITLE
Ansible role tweaks

### ISSUE THREAD

**Issue by NaurisSadovskis** [crowdcube/ansible-role-cc_jenkins#3]
There are few things we've noticed that need improving:

1) We need to have AWS CLI installed, after which we should be able to run:
```
$ aws configure set aws_access_key_id {{ access_key }}
$ aws configure set aws_secret_access_key {{ secret_key }}
$ aws configure set default.region {{ aws_region }}
```
This will enable us to get rid of the files generated and placed in `$HOME` (sorry @darkraiden !) 

2) We should add shell to Jenkins user using Ansible:
```
- name: Enable shell for Jenkins user
  user:
    name: jenkins
    shell: /bin/bash
```

3) `kubectl`, `kops`, `helm` binaries should be installed in `/usr/bin` directory as `/bin/bash` as current binary path is not in `$PATH`:
```
-bash-4.2$ whoami
jenkins
-bash-4.2$ which helm
/usr/bin/which: no helm in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
-bash-4.2$
```

4) We should remove references to installing plugins using using geerlingguy's role as once Github is enabled, we cannot use jenkins admin user credentials to install roles. 

I suggest, we try and create a groovy template that installs plugins in the same way we have have configured GitHub Oauth.

**Comment by darkraiden** [comment]
Will use [this role](https://github.com/darkraiden/ansible-role-aws_pip) to install the aws cli and since we configure the aws creds and config with the role itself, I removed the `aws_config.yml` file

**Comment by NaurisSadovskis** [comment]
Few more improvements coming your way! 

5) We need to add `restart jenkins` handler after applying .groovy script. This will allow to re-load latest settings. 

6) Plugin installation. I've added 'crowdcube-build' as admin user so it has permissions to install Jenkins plugins via `jenkins-cli` jar. 

We need to modify playbook so it does the following:
```
cd {{ jenkins_home }}
curl -O http://localhost:8080/jnlpJars/jenkins-cli.jar
java -jar jenkins-cli.jar -auth crowdcube-build:<token-here> -s http://localhost:8080 install-plugin git github-oauth plugin1 plugin3
```

From my end, I'll configure ELB to check `/robots.txt`, as currently Jenkins is getting 403 Error when trying to access root (`/`). 

Happy days!

**Comment by darkraiden** [comment]
Can't use the AWS role because the Jenkins user is not enabled by default, therefore it won't configure its creds properly. Adding the AWS config manually!

**Comment by darkraiden** [comment]
Pull Request for points 1 and 4 can be found [here](https://github.com/crowdcube/ansible-role-cc_jenkins/pull/4)

**Comment by darkraiden** [comment]
Pull Request for point 2 is PR #5

**Comment by darkraiden** [comment]
Pull request for point 5 and 6 is PR #6

**Comment by darkraiden** [comment]
I am on fire!
![https://media.giphy.com/media/yr7n0u3qzO9nG/giphy.gif][https://media.giphy.com/media/yr7n0u3qzO9nG/giphy.gif]

**Comment by darkraiden** [comment]
Fixed pretty much all the points listed above. Closing this for now.
